### ISSUE TITLE
Keyboard support for controls

### ISSUE THREAD

**Issue by tanvirchahal** [tanvirchahal/toy-robot#1]
Keyboard support can be added for the controls. 

User should be able to use up, left and right keys to control the toy robot.

### Acceptance Criteria
* [ ] Up key makes the robot move ahead
* [ ] Right key makes the robot move right
* [ ] Left key makes the robot move left

### Tasks
* [ ] Implement events on keypress
* [ ] Call appropriate functions
* [ ] Test
* [ ] Deploy
