### ISSUE TITLE
Update background image for game

### ISSUE THREAD

**Issue by tanvirchahal** [tanvirchahal/toy-robot#2]
The game can be more inviting by the usage of interesting backgrounds/animations

### Acceptance Criteria
* [ ] New backgrounds are implemented
* [ ] Different screensizes are supported

### Tasks
* [ ] Find background / animations
* [ ] Implement
* [ ] Test
* [ ] Deploy
